import csv
from pathlib import Path
from pypdf import PdfReader, PdfWriter
import tempfile
from datetime import datetime


def welcome():
    print("\nWelcome to the PDF Tool!\n")


def user_prompt():
    print("=" * 40)
    print("Press 1 to Combine PDFs.")
    print("Press 2 to Create PDF Bookmarks.")
    print("Press 3 to do both!")
    print("=" * 40)
    print("\n")

    return input("User Choice: ").strip()


def validate_prompt():
    while True:
        mode_choice = user_prompt()

        if mode_choice == "1":
            return 1

        elif mode_choice == "2":
            return 2

        elif mode_choice == "3":
            return 3

        else:
            print("\n")
            print(f"Please try again. '{mode_choice}' is not an option.")
            print("\n")


def yes_no_prompt(prompt: str) -> bool:
    while True:
        choice = input(prompt).strip().lower()

        if choice in {"y", "yes"}:
            return True

        if choice in {"n", "no"}:
            return False

        print("Please enter yes or no.\n")


def clean_path_input(user_input: str) -> str:
    """
    Cleans a user-entered path.

    Allows paths wrapped in matching single or double quotes:
        "/path/to/file.pdf"
        '/path/to/file.pdf'

    It only removes quotes if they wrap the entire path.
    """
    path = user_input.strip()

    if len(path) >= 2 and path[0] == path[-1] and path[0] in {"'", '"'}:
        path = path[1:-1].strip()

    return path


def is_pdf(filepath: str) -> bool:
    path = Path(filepath)

    if not path.is_file():
        return False

    if path.suffix.lower() != ".pdf":
        return False

    try:
        with path.open("rb") as f:
            header = f.read(4)
            return header == b"%PDF"
    except OSError:
        return False


def is_csv(filepath: str) -> bool:
    path = Path(filepath)

    if not path.is_file():
        return False

    if path.suffix.lower() != ".csv":
        return False

    try:
        with path.open(newline="", encoding="utf-8") as csvfile:
            reader = csv.DictReader(csvfile)

            if reader.fieldnames is None:
                return False

            required_columns = {"title", "page"}
            return required_columns.issubset(set(reader.fieldnames))

    except Exception:
        return False


def get_pdf_path(prompt="Enter a PDF filepath: ") -> str:
    while True:
        user_path = clean_path_input(input(prompt))

        if is_pdf(user_path):
            return user_path

        print("Invalid PDF. Please try again.\n")


def get_csv_path() -> str:
    while True:
        user_path = clean_path_input(input("Enter a CSV filepath: "))

        if is_csv(user_path):
            return user_path

        print("Invalid CSV. Please try again.\n")


def get_output_pdf_path(prompt="Enter the path for the output PDF, including .pdf extension: ") -> str:
    while True:
        output_path = clean_path_input(input(prompt))
        path = Path(output_path)

        if path.suffix.lower() != ".pdf":
            print("Output file must end in .pdf. Please try again.\n")
            continue

        if path.exists() and path.is_dir():
            print("Output path is a directory. Please provide a full filename.\n")
            continue

        if path.parent != Path(".") and not path.parent.exists():
            print("The output folder does not exist. Please try again.\n")
            continue

        return output_path


def get_output_csv_path(prompt="Enter the path for the autogenerated CSV, including .csv extension: ") -> str:
    while True:
        output_path = clean_path_input(input(prompt))
        path = Path(output_path)

        if path.suffix.lower() != ".csv":
            print("Output file must end in .csv. Please try again.\n")
            continue

        if path.exists() and path.is_dir():
            print("Output path is a directory. Please provide a full filename.\n")
            continue

        if path.parent != Path(".") and not path.parent.exists():
            print("The output folder does not exist. Please try again.\n")
            continue

        return output_path


def get_pdf_creation_time(pdf_path: str) -> float:
    """
    Returns a timestamp used for sorting PDFs by creation time.

    On Windows/macOS, this usually represents creation time.
    On some Unix/Linux systems, st_ctime may represent metadata change time,
    not true creation time.
    """
    path = Path(pdf_path)
    stat = path.stat()

    # macOS may support true birth/creation time
    if hasattr(stat, "st_birthtime"):
        return stat.st_birthtime

    # Windows creation time; Unix metadata change time
    return stat.st_ctime


def write_pdf_order_txt(pdf_paths: list[str]) -> str:
    """
    Creates a temporary text file listing the PDF merge order.
    Returns the temporary txt filepath.
    """
    temp_file = tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".txt",
        prefix="pdf_merge_order_",
        delete=False,
        encoding="utf-8"
    )

    with temp_file as file:
        file.write("PDF Merge Order\n")
        file.write("=" * 40 + "\n")
        file.write("Order: Oldest created first -> newest created last\n\n")

        for index, pdf_path in enumerate(pdf_paths, start=1):
            created_timestamp = get_pdf_creation_time(pdf_path)
            created_readable = datetime.fromtimestamp(created_timestamp).strftime(
                "%Y-%m-%d %H:%M:%S"
            )

            file.write(f"{index}. {pdf_path}\n")
            file.write(f"   Created: {created_readable}\n\n")

    return temp_file.name


def get_pdf_paths_from_directory() -> tuple[list[str], str]:
    """
    Prompts the user for a directory, finds PDFs in that directory,
    sorts them by oldest created first, and writes the order
    to a temporary txt file.

    Returns:
        pdf_paths, order_txt_path
    """
    while True:
        directory_input = clean_path_input(
            input("Enter the target directory containing PDFs: ")
        )
        directory = Path(directory_input)

        if not directory.exists():
            print("That directory does not exist. Please try again.\n")
            continue

        if not directory.is_dir():
            print("That path is not a directory. Please try again.\n")
            continue

        pdf_paths = []

        for path in directory.iterdir():
            if path.is_file() and path.suffix.lower() == ".pdf":
                if is_pdf(str(path)):
                    pdf_paths.append(str(path))

        if len(pdf_paths) < 2:
            print("The directory must contain at least 2 valid PDF files.\n")
            continue

        # Sort oldest-created first, newest-created last
        pdf_paths.sort(
            key=lambda pdf_path: get_pdf_creation_time(pdf_path),
            reverse=False
        )

        order_txt_path = write_pdf_order_txt(pdf_paths)

        print("\nPDFs found and sorted by oldest created first:\n")

        for index, pdf_path in enumerate(pdf_paths, start=1):
            created_timestamp = get_pdf_creation_time(pdf_path)
            created_readable = datetime.fromtimestamp(created_timestamp).strftime(
                "%Y-%m-%d %H:%M:%S"
            )

            print(f"{index}. {pdf_path}")
            print(f"   Created: {created_readable}")

        print(f"\nMerge order saved to temporary txt file:")
        print(order_txt_path)
        print()

        return pdf_paths, order_txt_path


def get_pdf_paths_manually() -> tuple[list[str], None]:
    """
    Original method: user enters PDF paths one at a time.

    Returns:
        pdf_paths, None
    """
    pdf_paths = []

    print("Enter PDF filepaths one at a time.")
    print("Press Enter with no input when you are finished.\n")

    while True:
        user_path = clean_path_input(
            input("Enter a PDF filepath, or press Enter to finish: ")
        )

        if user_path == "":
            if len(pdf_paths) >= 2:
                return pdf_paths, None
            else:
                print("Please enter at least 2 PDF files to combine.\n")
                continue

        if is_pdf(user_path):
            pdf_paths.append(user_path)
            print(f"Added: {user_path}\n")
        else:
            print("Invalid PDF. Please try again.\n")


def get_pdf_paths_for_combine() -> tuple[list[str], str | None]:
    """
    Lets the user choose how to provide PDFs for combining.

    Method 1:
        Target directory, auto-sort by creation time,
        and generate temporary txt merge-order file.

    Method 2:
        Manually enter multiple PDF paths.

    Returns:
        pdf_paths, order_txt_path

    order_txt_path will be None if manual entry was used.
    """
    while True:
        print("\nChoose PDF combine input method:")
        print("=" * 40)
        print("Press 1 to select a target directory.")
        print("Press 2 to manually enter PDF paths.")
        print("=" * 40)

        choice = input("User Choice: ").strip()

        if choice == "1":
            return get_pdf_paths_from_directory()

        elif choice == "2":
            return get_pdf_paths_manually()

        else:
            print(f"'{choice}' is not an option. Please try again.\n")


def get_bookmark_title_from_pdf_path(pdf_path: str) -> str:
    """
    Turns '/some/folder/My File.pdf' into 'My File'.
    Used as the default merge-point bookmark title.
    """
    return Path(pdf_path).stem


def write_bookmark_csv(rows: list[dict], csv_path: str):
    """
    Writes bookmark information to a CSV file.

    Expected row format:
    {
        "title": "Bookmark title",
        "page": 1,
        "parent": ""
    }
    """
    with open(csv_path, "w", newline="", encoding="utf-8") as csvfile:
        fieldnames = ["title", "page", "parent"]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()

        for row in rows:
            writer.writerow({
                "title": row["title"],
                "page": row["page"],
                "parent": row.get("parent", "")
            })

    print(f"Autogenerated bookmark CSV saved as '{csv_path}'.")


def combine_pdfs(
    pdf_paths: list[str],
    output_path: str,
    create_merge_bookmarks: bool = False
) -> list[dict]:
    """
    Combines PDFs.

    If create_merge_bookmarks is True, creates PDF bookmarks at each file's
    starting page in the merged PDF.

    Returns a list of bookmark rows with correct merged-page numbers.
    """
    writer = PdfWriter()
    merge_bookmark_rows = []

    current_page_number = 1

    for pdf_path in pdf_paths:
        reader = PdfReader(pdf_path)

        title = get_bookmark_title_from_pdf_path(pdf_path)
        start_page_number = current_page_number
        start_page_index = start_page_number - 1

        print(f"Merging '{pdf_path}' starting on page {start_page_number}.")

        for page in reader.pages:
            writer.add_page(page)
            current_page_number += 1

        merge_bookmark_rows.append({
            "title": title,
            "page": start_page_number,
            "parent": ""
        })

        if create_merge_bookmarks:
            writer.add_outline_item(
                title=title,
                page_number=start_page_index
            )

    with open(output_path, "wb") as output_file:
        writer.write(output_file)

    print(f"\nCombined PDF saved as '{output_path}'.")

    return merge_bookmark_rows


def add_bookmarks_from_csv(pdf_path: str, csv_path: str, output_path: str):
    reader = PdfReader(pdf_path)
    writer = PdfWriter()

    # Copy all pages from original PDF to new PDF
    for page in reader.pages:
        writer.add_page(page)

    # Store bookmark references by title so children can attach to parents
    bookmark_refs = {}

    with open(csv_path, newline="", encoding="utf-8") as csvfile:
        reader_csv = csv.DictReader(csvfile)

        for row in reader_csv:
            title = row["title"].strip()
            parent_title = row.get("parent", "").strip()
            page_text = row["page"].strip()

            if not title:
                print("Warning: Skipping row with empty title.")
                continue

            try:
                # CSV page numbers are assumed to be 1-based
                page_number = int(page_text) - 1
            except ValueError:
                print(f"Warning: Invalid page number '{page_text}' for '{title}'. Skipping.")
                continue

            if page_number < 0 or page_number >= len(reader.pages):
                print(f"Warning: Page {page_text} out of range for '{title}'. Skipping.")
                continue

            parent_ref = None

            if parent_title:
                parent_ref = bookmark_refs.get(parent_title)

                if parent_ref is None:
                    print(
                        f"Warning: Parent bookmark '{parent_title}' not found for '{title}'. "
                        "Adding as top-level bookmark."
                    )

            bookmark_ref = writer.add_outline_item(
                title=title,
                page_number=page_number,
                parent=parent_ref
            )

            bookmark_refs[title] = bookmark_ref

    with open(output_path, "wb") as output_file:
        writer.write(output_file)

    print(f"New PDF with bookmarks saved as '{output_path}'.")


def pdf_combine() -> str:
    print("\nPDF Combine Selected\n")

    pdf_paths, order_txt_path = get_pdf_paths_for_combine()

    if order_txt_path is not None:
        print(f"Merge order txt file created at: {order_txt_path}\n")

    create_merge_bookmarks = yes_no_prompt(
        "Create bookmarks at each file merge point? yes/no: "
    )

    output_path = get_output_pdf_path("Enter output path for combined PDF: ")

    combine_pdfs(
        pdf_paths=pdf_paths,
        output_path=output_path,
        create_merge_bookmarks=create_merge_bookmarks
    )

    return output_path


def pdf_bookmark(pdf_path=None):
    print("\nPDF Bookmark Selected\n")

    if pdf_path is None:
        pdf_path = get_pdf_path("Enter the PDF filepath to bookmark: ")

    print(f"Using PDF: {pdf_path}")

    csv_path = get_csv_path()
    print(f"Using CSV: {csv_path}")

    output_path = get_output_pdf_path("Enter output path for bookmarked PDF: ")

    add_bookmarks_from_csv(pdf_path, csv_path, output_path)


def pdf_both():
    print("\nCombine PDFs and Add Bookmarks Selected\n")

    pdf_paths, order_txt_path = get_pdf_paths_for_combine()

    if order_txt_path is not None:
        print(f"Merge order txt file created at: {order_txt_path}\n")

    intermediate_pdf_path = get_output_pdf_path(
        "Enter output path for the temporary combined PDF: "
    )

    csv_path = get_output_csv_path(
        "Enter output path for the autogenerated bookmark CSV: "
    )

    final_pdf_path = get_output_pdf_path(
        "Enter final output path for combined bookmarked PDF: "
    )

    print("\nCombining PDFs and tracking merge-page numbers...\n")

    merge_bookmark_rows = combine_pdfs(
        pdf_paths=pdf_paths,
        output_path=intermediate_pdf_path,
        create_merge_bookmarks=False
    )

    write_bookmark_csv(merge_bookmark_rows, csv_path)

    print("\nThe autogenerated bookmark CSV has been created.")
    print("You may now open the CSV file and edit the bookmark titles.")
    print("You can also edit the parent column if you want nested bookmarks.")
    print("Make sure to save the CSV before continuing.")
    print(f"\nCSV file: {csv_path}")

    while True:
        input("\nPress Enter after you have finished editing and saving the CSV...")

        if is_csv(csv_path):
            break

        print("\nThe CSV appears to be invalid.")
        print("Please make sure it still has at least these columns:")
        print("title,page")
        print("Then save it and try again.")

    print("\nAdding edited bookmarks to combined PDF...\n")

    add_bookmarks_from_csv(
        pdf_path=intermediate_pdf_path,
        csv_path=csv_path,
        output_path=final_pdf_path
    )


def main():
    welcome()

    choice = validate_prompt()

    if choice == 1:
        pdf_combine()

    elif choice == 2:
        pdf_bookmark()

    elif choice == 3:
        pdf_both()


if __name__ == "__main__":
    main()